theme: jekyll-theme-minimal
title: Charles Puelz's website
description: Welcome to my website! I am finishing a position at the Courant Institute and in August will start as an Assistant Professor at Baylor College of Medicine
logo: images/Puelz.Charles.JPG
