theme: jekyll-theme-minimal
title: Charles Puelz's website
description: Welcome! <br><br> I am finishing a position at the Courant Institute and will start as an Assistant Professor at Baylor College of Medicine in August 2020.
logo: images/Puelz.Charles.JPG
